platform :ios, '8.0'

use_frameworks!

target "MVCDemo" do


pod 'Alamofire', '4.5.1'
pod 'SwiftyJSON','3.1.4'
pod 'ObjectMapper', '~> 2.0'
pod 'AlamofireObjectMapper','4.1.0'
pod 'SwiftyJSON','3.1.4'
end
